version: "1.0"

services:
  x-list-manager:
    type: scheduled
    schedule: "0 19 * * *"  # UTC時間で4:00 JST
    container:
      image: ${IMAGE}
      command: ["python", "core.py"]
    resources:
      cpu: 1000
      memory: 512Mi
    env:
      - name: TZ
        value: Asia/Tokyo
    secrets:
      - x-api-key
      - x-api-secret
      - x-access-token
      - x-access-secret
      - bearer-token