version: "1.0"

services:
  x-list-manager:
    type: scheduled
    schedule: "0 19 * * *"  # UTC時間で19時（日本時間4:00）
    container:
      image: ${IMAGE_URL}
      command: ["python", "main.py"]
    resources:
      cpu: 2000
      memory: 1024Mi
    env:
      - name: TZ
        value: Asia/Tokyo
      - name: BEARER_TOKEN
        secret: bearer-token
      - name: X_API_KEY
        secret: x-api-key
      - name: X_API_SECRET
        secret: x-api-secret
      - name: X_ACCESS_TOKEN
        secret: x-access-token
      - name: X_ACCESS_SECRET
        secret: x-access-secret
    healthChecks:
      http:
        path: /health
        port: 8080
        interval: 30
        timeout: 10